<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17934" started-at="2018-06-27T13:44:33Z" finished-at="2018-06-27T13:44:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17934" started-at="2018-06-27T13:44:33Z" finished-at="2018-06-27T13:44:51Z">
      <class name="com.org.rayban.DemoTest">
        <test-method status="PASS" signature="navigateToLoginPagae()[pri:0, instance:com.org.rayban.DemoTest@13a5fe33]" name="navigateToLoginPagae" duration-ms="15202" started-at="2018-06-27T13:44:33Z" finished-at="2018-06-27T13:44:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToLoginPagae -->
        <test-method status="FAIL" signature="successfullLogin()[pri:0, instance:com.org.rayban.DemoTest@13a5fe33]" name="successfullLogin" duration-ms="2693" started-at="2018-06-27T13:44:48Z" finished-at="2018-06-27T13:44:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[validation failed expected [Learn Git and GitHub without any code] but found [Learn Git and GitHub without any code!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: validation failed expected [Learn Git and GitHub without any code] but found [Learn Git and GitHub without any code!]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.org.rayban.buisnessLib.loginBuissnessScenario.validateLoginSuccessful(loginBuissnessScenario.java:43)
at com.org.rayban.DemoTest.successfullLogin(DemoTest.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successfullLogin -->
      </class> <!-- com.org.rayban.DemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
